services:
  - type: web
    name: stalker-browser
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATA_DIR
        value: /app/data
      - key: XTREAM_PORT
        value: 3000
